/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'gpio_using_polling_method' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f0xx.h"

/* Keil::Device&Standalone:STM32Cube HAL:COMMON@1.11.3 */
#define RTE_DEVICE_HAL_COMMON
/* Keil::Device&Standalone:STM32Cube HAL:CORTEX@1.11.3 */
#define RTE_DEVICE_HAL_CORTEX
/* Keil::Device&Standalone:STM32Cube HAL:FLASH@1.11.3 */
#define RTE_DEVICE_HAL_FLASH
/* Keil::Device&Standalone:STM32Cube HAL:GPIO@1.11.3 */
#define RTE_DEVICE_HAL_GPIO
/* Keil::Device&Standalone:STM32Cube HAL:RCC@1.11.3 */
#define RTE_DEVICE_HAL_RCC
/* Keil::Device&Standalone:Startup@1.0.0 */
#define RTE_DEVICE_STARTUP_STM32F0XX    /* Device Startup for STM32F0 */


#endif /* RTE_COMPONENTS_H */
